"""2

Revision ID: f6e7c2079e61
Revises: 4f2916992bc7
Create Date: 2024-03-04 22:26:06.528670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e7c2079e61'
down_revision: Union[str, None] = '4f2916992bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_products_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_users_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'products_id')
    op.drop_column('orders', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('products_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_users_id_fkey', 'orders', 'users', ['users_id'], ['id'])
    op.create_foreign_key('orders_products_id_fkey', 'orders', 'products', ['products_id'], ['id'])
    # ### end Alembic commands ###
